# For more info on HTTP files go to https://aka.ms/vs/httpfile
###
GET http://localhost:5237/games/

###
GET http://localhost:5237/genres/



###

POST http://localhost:5237/games
Content-Type: application/json

{
  "name": "Minecraft",
  "genreId": 3,
  "price": 27.0,
  "releaseDate": "2015-01-15"
}
###
PUT http://localhost:5237/games/5
Content-Type: application/json

{

  "name": "ff XIV",
  "genreId": 1,
  "price": 27.0,
  "releaseDate": "2011-01-15"
}

###
DELETE http://localhost:5237/games/8
